<?php

use divengine\div;

class ElementView extends div
{

    public $id = 5;

    public $class = 5;

    public $childs = [];

    public $properties = [];

    public function __construct($src = null, $items = null, $ignore = [])
    {
        if ($src === null) {
            $src = get_class($this);
        }
        parent::__construct($src, $items, $ignore);
    }

    public function addProperty($name, $value)
    {
        $this->properties[$name] = $value;
    }

    public function addProperties($properties)
    {
        $this->properties = self::cop($this->properties, $properties);
    }

    public function addChild($child, $key = null)
    {
        if ($key !== null) {
            $this->childs[$key] = $child;
        } else {
            $this->childs[] = $child;
        }

    }
}

class LabelView extends ElementView
{

    public $text = '';

    public $for = '';
}

class FieldView extends ElementView
{

    public $name;

    public $type = 'text';

    public $label = null;

    public $value = null;
}

class FormView extends ElementView
{

    public $action = '/';

    public $method = 'POST';

    public function __construct($src = null, $items = null, $ignore = [])
    {
        parent::__construct($src, $items, $ignore);
    }

    public function addChild($child, $key = null)
    {
        $key = $child->id ?? null;
        if ($key === null) $key = $child->name ?? null;

        parent::addChild($child, $key); // TODO: Change the autogenerated stub
    }
}